In [1]:
import pandas as pd
import numpy as np

## These are the Tables I'll be defining variables for

In [3]:
["hn_stats_summary_w_agg.json", "389 kB"]
["top100_AMT_Salt_Contributed.json", "58.6 kB"]
["top100_Overall_Saltiest.json", "57.5 kB"]
["top100_QTY_Salty_Comments.json", "57.7 kB"]
["top100_Saltiest_Trolls.json", "70.5 kB"]
["hn_commentor_summary.csv", "2.9 GB"];

In [14]:
df2 = pd.read_csv("hn_commentor_summary.csv")
df2.rename(columns={"average_slt_oall":'avg_slt_oall',"count_comments":"cnt_cmnts_oall", "time_of_last_comment": "time_cmnt_lst", "time_of_first_comment": "time_cmnt_fst"}, inplace= True)

In [22]:
# hn_commentor_summary
df3 = df2[["commentor", # Name of commentor.
          "time_cmnt_lst", # Most recent comment time in Dataset.
          "time_cmnt_fst", # First HN comment time.
          "cnt_cmnts_oall", # Count of total number of comments. 
          "sum_slt_oall", # Total Salt Score Overall. (All Salty + NonSalty Scores added up.)
          "avg_slt_oall", # Average Comment Salt Score across all comments. 
          "cnt_slt_s", # Count of JUST salty comments. 
          "sum_slt_s", # Total Salt Score of Salty Comments
          "avg_slt_s", # Average Salt Score of Salty Comments
          "rank_lt_amt_slt", # Rank: Lifetime Salt Scores Total of Salty comments only.
          "rank_lt_qty_sc", # Rank: Lifetime quantity of "Salty Comments" contributed.
          "rank_oall_slt", # Rank: Lifetime overall "Salt Score" total of All Salty + NonSalty comments. 
          "rank_slt_trolls", # Rank: *ONLY TROLL ACCOUNTS* Lifetime overall "Salt Score" total. (Troll accounts are accounts that *ONLY* have salty posts.)
          "top_cmnts_s", # List of 50 Top Salty Comments. 
          "monthly_plot"]].copy() # List of every month of activity for plotting.

#     Stats in the `montly_plot` list are:
#        y_m: Year-Month period of stat aggregation from the `month-text` group.
#        c_h: Stat, count of Happy Comments for the month.
#        c_s: Stat, count of Salty Comments for the month.
#       t_h: Stat, total (sum) of Happy Comment Scores for the month.
#       t_s: Stat, total (sum) of Salty Comment Scores for the month.

In [ ]:
"""
6	hn_sum_slt_oall - All the Salty & NotSalty Scores added up. 
7	hn_sum_slt_s - All the Salty (Only Salty) Scores added up. 
3	hn_avg_oall
4	hn_cnt_slt_s
5	hn_count_oall - Count of all comments. 

"""

In [23]:
df3.columns

Index(['commentor', 'time_cmnt_lst', 'time_cmnt_fst', 'cnt_cmnts_oall',
       'sum_slt_oall', 'avg_slt_oall', 'cnt_slt_s', 'sum_slt_s', 'avg_slt_s',
       'rank_lt_amt_slt', 'rank_lt_qty_sc', 'rank_oall_slt', 'rank_slt_trolls',
       'top_cmnts_s', 'monthly_plot'],
      dtype='object')

In [43]:
# Get some Sort by Total Salt
df3.sort_values(by=["rank_lt_amt_slt"], inplace= True)
df_a = df3.iloc[0:100,:]

In [44]:
# Get some Sort by Total Salt
df3.sort_values(by=["rank_lt_qty_sc"], inplace= True)
df_b = df3.iloc[0:100,:]

In [45]:
# Get some Overall Saltyness Ranked Scores
df3.sort_values(by=["rank_oall_slt"], inplace= True)
df_c = df3.iloc[0:100,:]

In [46]:
# Get some Overall Saltyness Ranked Scores
df3.sort_values(by=["rank_slt_trolls"], inplace= True)
df_d = df3.iloc[0:100,:]

In [47]:
# Get some by Earliest Post 
df3.sort_values(by=["time_cmnt_fst"], inplace= True)
df_e = df3.iloc[0:300,:]

In [48]:
# Join up all my samples. 
df_export = pd.concat([df_a,df_b,df_c,df_d,df_e])

In [49]:
df_export.shape

(700, 15)

In [50]:
# Get rid of duplicates
df_export = df_export.drop_duplicates()

In [51]:
df_export.shape

(612, 15)

In [52]:
# Save to json
df_export.to_json("hn_commentor_summary_test.json", orient='records')

In [12]:
df = pd.read_json("top100_AMT_Salt_Contributed.json")
df.head(1000)

,commentor,rank_lt_amt_slt,sum_slt_s,top_salty_comment
0,tptacek,1,-1172.664693,"[{'commentor': 'tptacek', 'comment_time': 1523..."
1,dang,2,-738.633676,"[{'commentor': 'dang', 'comment_time': 1453407..."
2,DanBC,3,-627.360008,"[{'commentor': 'DanBC', 'comment_time': 136870..."
3,jacquesm,4,-541.817948,"[{'commentor': 'jacquesm', 'comment_time': 152..."
4,mikeash,5,-433.753479,"[{'commentor': 'mikeash', 'comment_time': 1484..."
5,icebraining,6,-405.850725,"[{'commentor': 'icebraining', 'comment_time': ..."
6,coldtea,7,-369.202170,"[{'commentor': 'coldtea', 'comment_time': 1536..."
7,jrockway,8,-342.707408,"[{'commentor': 'jrockway', 'comment_time': 121..."
8,TeMPOraL,9,-317.315165,"[{'commentor': 'TeMPOraL', 'comment_time': 143..."
9,dragonwriter,10,-307.179746,"[{'commentor': 'dragonwriter', 'comment_time':..."
10,rbanffy,11,-304.309225,"[{'commentor': 'rbanffy', 'comment_time': 1505..."
11,StavrosK,12,-301.949349,"[{'commentor': 'StavrosK', 'comment_time': 143..."
12,rayiner,13,-301.734512,"[{'commentor': 'rayiner', 'comment_time': 1352..."
13,sp332,14,-299.490765,"[{'commentor': 'sp332', 'comment_time': 136855..."
14,JoeAltmaier,15,-299.325053,"[{'commentor': 'JoeAltmaier', 'comment_time': ..."
15,pjmlp,16,-298.964716,"[{'commentor': 'pjmlp', 'comment_time': 148424..."
16,eru,17,-287.322479,"[{'commentor': 'eru', 'comment_time': 14047851..."
17,pavel_lishin,18,-273.782059,"[{'commentor': 'pavel_lishin', 'comment_time':..."
18,Tichy,19,-267.626175,"[{'commentor': 'Tichy', 'comment_time': 127653..."
19,gaius,20,-266.547536,"[{'commentor': 'gaius', 'comment_time': 150598..."
20,pjc50,21,-262.377040,"[{'commentor': 'pjc50', 'comment_time': 140369..."
21,anigbrowl,22,-262.086493,"[{'commentor': 'anigbrowl', 'comment_time': 12..."
22,toomuchtodo,23,-260.832894,"[{'commentor': 'toomuchtodo', 'comment_time': ..."
23,maxerickson,24,-249.961119,"[{'commentor': 'maxerickson', 'comment_time': ..."
24,chris_wot,25,-248.630874,"[{'commentor': 'chris_wot', 'comment_time': 14..."
25,rhizome,26,-247.825112,"[{'commentor': 'rhizome', 'comment_time': 1393..."
26,wmf,27,-244.014470,"[{'commentor': 'wmf', 'comment_time': 14068481..."
27,Dylan16807,28,-237.232850,"[{'commentor': 'Dylan16807', 'comment_time': 1..."
28,stcredzero,29,-235.141146,"[{'commentor': 'stcredzero', 'comment_time': 1..."
29,ars,30,-222.307385,"[{'commentor': 'ars', 'comment_time': 13612314..."
...,...,...,...,...
70,astrodust,71,-155.104359,"[{'commentor': 'astrodust', 'comment_time': 13..."
71,tlrobinson,72,-152.863275,"[{'commentor': 'tlrobinson', 'comment_time': 1..."
72,rmc,73,-152.155936,"[{'commentor': 'rmc', 'comment_time': 14295223..."
73,dllthomas,74,-150.391727,"[{'commentor': 'dllthomas', 'comment_time': 13..."
74,rdl,75,-150.159831,"[{'commentor': 'rdl', 'comment_time': 13733509..."
75,krapp,76,-149.741419,"[{'commentor': 'krapp', 'comment_time': 138811..."
76,draw_down,77,-149.322727,"[{'commentor': 'draw_down', 'comment_time': 15..."
77,hueving,78,-147.532507,"[{'commentor': 'hueving', 'comment_time': 1444..."
78,walshemj,79,-146.440455,"[{'commentor': 'walshemj', 'comment_time': 137..."
79,nitrogen,80,-142.328340,"[{'commentor': 'nitrogen', 'comment_time': 144..."
80,AnimalMuppet,81,-140.165230,"[{'commentor': 'AnimalMuppet', 'comment_time':..."
81,mtgx,82,-139.225838,"[{'commentor': 'mtgx', 'comment_time': 1349346..."
82,voltagex_,83,-138.507418,"[{'commentor': 'voltagex_', 'comment_time': 13..."
83,guelo,84,-137.296720,"[{'commentor': 'guelo', 'comment_time': 142241..."
84,maxxxxx,85,-135.537585,"[{'commentor': 'maxxxxx', 'comment_time': 1545..."
85,kazinator,86,-135.258403,"[{'commentor': 'kazinator', 'comment_time': 14..."
86,MichaelGG,87,-135.238940,"[{'commentor': 'MichaelGG', 'comment_time': 14..."
87,PhasmaFelis,88,-134.615237,"[{'commentor': 'PhasmaFelis', 'comment_time': ..."
88,sctb,89,-133.684693,"[{'commentor': 'sctb', 'comment_time': 1474059..."
89,Kiro,90,-133.451491,"[{'commentor': 'Kiro', 'comment_time': 1543868..."
90,jonknee,91,-133.392878,"[{'commentor': 'jonknee', 'comment_time': 1450..."
91,scott_s,92,-133.385019,"[{'commentor': 'scott_s', 'comment_time': 1380..."
92,jerf,93,-133.066517,"[{'commentor': 'jerf', 'comment_time': 1349361..."
93,nailer,94,-132.251150,"[{'commentor': 'nailer', 'comment_time': 13981..."
94,api,95,-131.643550,"[{'commentor': 'api', 'comment_time': 14991171..."
95,jlgreco,96,-131.133584,"[{'commentor': 'jlgreco', 'comment_time': 1372..."
96,WalterBright,97,-130.554514,"[{'commentor': 'WalterBright', 'comment_time':..."
97,InclinedPlane,98,-128.718075,"[{'commentor': 'InclinedPlane', 'comment_time'..."
98,ck2,99,-126.566041,"[{'commentor': 'ck2', 'comment_time': 13514762..."
99,JumpCrisscross,100,-125.730167,"[{'commentor': 'JumpCrisscross', 'comment_time..."

In [9]:
df_a = pd.DataFrame(df.columns, columns=["Column_ID"])
df_a["Stats Group"] = [["HN Overall"]]

                Column_ID
0           csc_cnt_slt_s
1           csc_commentor
2   csc_top_salty_comment
3             hn_avg_oall
4            hn_cnt_slt_s
5           hn_count_oall
6         hn_sum_slt_oall
7            hn_sum_slt_s
8   scp_comment_saltiness
9           scp_commentor
10  scp_top_salty_comment
11          sos_commentor
12       sos_sum_slt_oall
13  sos_top_salty_comment
14          ssc_commentor
15          ssc_sum_slt_s
16  ssc_top_salty_comment

In [ ]:
df_a["Descriptive Name"] = [
    ["CSC: Count of Salty Comments RANKING; CNT_SLT_S: Count of SALTY comments."]
    
]

In [10]:
df.columns

Index(['csc_cnt_slt_s', 'csc_commentor', 'csc_top_salty_comment',
       'hn_avg_oall', 'hn_cnt_slt_s', 'hn_count_oall', 'hn_sum_slt_oall',
       'hn_sum_slt_s', 'scp_comment_saltiness', 'scp_commentor',
       'scp_top_salty_comment', 'sos_commentor', 'sos_sum_slt_oall',
       'sos_top_salty_comment', 'ssc_commentor', 'ssc_sum_slt_s',
       'ssc_top_salty_comment'],
      dtype='object')

In [ ]:
 'hn_avg_oall', 'hn_cnt_slt_s', 'hn_count_oall', 'hn_sum_slt_oall',
       'hn_sum_slt_s',